#!/bin/bash
clear
echo "America/Sao_Paulo" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime > /dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1
IP=$(wget -qO- ipv4.icanhazip.com)
clear
echo -e "\E[44;1;37m    INSTALANDO SITE DE SSH FREE by @Laael    \E[0m" 
echo ""
echo -e "\n\033[1;36mATUALIZANDO PACOTES, \033[1;33mAGUARDE...\033[0m"
apt-get update; apt-get upgrade -y &&
echo -e "\n\033[1;34mINSTALANDO DEPENDENCIAS \033[1;33mAGUARDE..."
apt-get install cron curl unzip -y &&
echo -e "\n\033[1;36mINSTALANDO O SERVIDOR APACHE, \033[1;33mAGUARDE...\033[0m"
apt-get install apache2 -y &&
apt-get install php5 libapache2-mod-php5 php5-mcrypt -y > /dev/null 2>&1
service apache2 restart &&
php5enmod mcrypt &&
service apache2 restart &&
apt-get install libssh2-1-dev libssh2-php -y &&
apt-get install php5-ssh2 -y &&
apt-get install php5-curl -y &&
service apache2 restart &&
clear
echo -e "\033[1;36m FINALIZANDO INSTALACAO\033[0m"
echo ""
echo -e "\033[1;33m AGUARDE..."
echo ""
cd /var/www
rm -R html /dev/null 2>&1
mkdir html /dev/null 2>&1
cd /var/www/html
wget https://painel.speednet.host/extras/sshfree/sshfree.zip &&
unzip sshfree.zip &&
rm -rf sshfree.zip &&
service apache2 restart &&
sleep 1
service apache2 restart &&
clear
echo ""
echo -e "\033[1;32m SHOW, SITE de SSH FREE INSTALADO COM SUCESSO!"
echo -e "\033[1;32m Configure seus servidores, localizacao abaixo:"
echo ""
echo -e "\033[1;36m Brasil:\033[1;37m free/gerar/brfree/config/config.php\033[0m"
echo -e "\033[1;36m Canada:\033[1;37m free/gerar/cafree/config/config.php\033[0m"
echo ""
cd
rm install
